### PR TITLE
Hello Microverse

### PR DESCRIPTION
**Pull request by yuvenalmash**
# Displays "Hello Microverse"
- New feature branch has added index.html, style.css, .gitignore, linters.yml, .hintrc, .stylelintrc.json and test.md

### CODE REVIEW

**Review by leonardodiasb — CHANGES_REQUESTED** [review]
# Required Changes ♻️ ⚠️ 🚦 

Hi @, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

mario_ladders

## Good points 👍 

✔️

## Aspects to improve ♻️

- [x] Check the comments under the review.
- [ ] I see that you added the `linters.yml` file in your project and that's working fine on Github, but in this project, you need to add the linters configurations locally for learning purposes. Kindly add the `.hintrc` and the `.stylelintrc.json` files to your project and follow the tutorial in [this article](https://github.com/microverseinc/linters-config/tree/master/html-css) to make sure they are correctly installed.
- [ ] The installation of the linters may add a `node_modules` folder, and this should be declared in the `.gitignore` file so this folder is not committed to the GitHub repository. Please make sure this folder is correctly declared.
- [ ] Your Pull Request should have a descriptive title telling you what changes are inside. Kindly try to be more professional with the PR title since you are dealing with other people that will review your code, the more professionalism involved in this situation the better the review and feedback you can get.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by yuvenalmash** [comment]
Thank you for the feedback.
I have have added the necessary files and installed the linters localy

**Review by codecaiine — CHANGES_REQUESTED** [review]
Hi @yuvenalmash, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- Good use of github flow :heavy_check_mark: 
- Good project implementation :heavy_check_mark: 

## Required Changes ♻️
- [ ] [REQUIRED] As the previous reviewer mentioned, please make sure that your pull Request title is descriptive which will help others know what you did inside your PR. :+1: 
_Check the comments under the review._

## Optional suggestions
- [ ] [OPTIONAL] Please add a descriptive README file to your project by using [this template](https://github.com/microverseinc/readme-template) and customize it. Please make sure to add and keep only the main header section and do not keep them empty. Also add a license in order to make it more professional :+1: 
- [ ] [OPTIONAL] Your project doesn't have a license. I would like to recommend using the [MIT license](https://choosealicense.com/licenses/mit/) - you can set it up quickly by [using templates available on GitHub](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository). You can also use [any other license](https://choosealicense.com/licenses/) if you wish and add the license link to a section in your readme dedicated for it in order to keep it more professional :+1: 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Please in your future project make your branch name more descriptive instead of feature :smile:  

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by yuvenalmash** [comment]
I have added a descriptive title, a license and updated the readme file

**Review by levy002 — CHANGES_REQUESTED** [review]
## Hello @yuvenalmash   , :wave:
### I'm Levy, your PR reviewer

Good job so far :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!



## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._

- [ ] Kindly make sure to add a good PR title as requested by the previous reviewers. It makes your repo looks more professional. :wink: 

  _Kindly watch this whole [video](https://www.youtube.com/watch?v=cnIDkME-gg0) to understand how to change your PR title_

    - ### Your PR title
  
   image

 - _**example PR title according to this project `Hello Microverse`**_

   

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by yuvenalmash** [comment]
hi @levy002, I have added the new title. Is everything alright now?

**Review by omarsalem7 — APPROVED** [review]
Hi @yuvenalmash 😊, 
# STATUS: APPROVED! 🥇 💯 

giphy

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 🚀 
Congratulations! 🎉 

## Highlights
✅ No linter errors. 
✅ The pull request has a good proper title
✅ Project has met all the technical aspects you needed for this project. Keep rocking! 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
